version: ‘3.3’

services:
  postgres:
    image: postgres:13
    env_file:
      .env
    ports:
      - 5432:5432
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    - ./sql/1_init.sql:/docker-entrypoint-initdb.d/1_init.sql
    restart: always
    networks:
        - default
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      .env
    ports:
      - 5050:80